name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    defaults:
      run:
        shell: powershell

    steps:
      - name: Configure Core RDP Settings
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force

          netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
          Restart-Service -Name TermService -Force

      - name: Create RDP User
        run: |
          $password = "SkyroPass2026!"
          $securePass = ConvertTo-SecureString$password -AsPlainText -Force
          New-LocalUser -Name "Skyro" -Password $securePass -AccountNeverExpires -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member "Skyro" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "Skyro" -ErrorAction SilentlyContinue
          
          Add-Content -Path $env:GITHUB_ENV -Value "RDP_PASS=$password"

      - name: Setup Direct Tunnel Gateway
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          choco install nodejs -y --no-progress
          npm install -g localtunnel

          Start-Process powershell -ArgumentList "-Command lt --port 3389" -WindowStyle Hidden

      - name: Maintain Connection
        run: |
          Write-Host "`n======================================================`n"
          Write-Host " USUARIO: Skyro"
          Write-Host " CONTRASEÑA: $env:RDP_PASS"
          Write-Host "`n======================================================`n"
          
          while ($true) {
              Write-Host "[$(Get-Date)] Servidor RDP activo y listo..."
              Start-Sleep -Seconds 300
          }
